### ISSUE TITLE
'capture-pane' return only the first line in some case

### ISSUE THREAD

**Issue by rockandska** [tmux-python/libtmux#188]
HI,

Did i miss something ?
This little script works with the python console, but display the 'send_keys' parameter instead of executing it.

```
bash-4.4$ cat test.py
import libtmux

tmux_session_name = 'test'

server = libtmux.Server()
session = server.new_session(tmux_session_name)
window = session.attached_window
pane = window.split_window(shell='PROMPT_COMMAND= bash --norc --noprofile')
pane.send_keys('cowsay hello')
print('\n'.join(pane.cmd('capture-pane', '-p').stdout))
bash-4.4$ 
bash-4.4$ python test.py
bash-4.4$  cowsay hello
bash-4.4$ 
bash-4.4$ pkill tmux
bash-4.4$ 
bash-4.4$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtmux
>>> tmux_session_name = 'test'
>>> server = libtmux.Server()
>>> session = server.new_session(tmux_session_name)
>>> window = session.attached_window
>>> pane = window.split_window(shell='PROMPT_COMMAND= bash --norc --noprofile')
>>> pane.send_keys('cowsay hello')
>>> print('\n'.join(pane.cmd('capture-pane', '-p').stdout))
bash-4.4$  cowsay hello
 _______
< hello >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
bash-4.4$
>>> 
bash-4.4$ 
```

Regards,

**Comment by rockandska** [comment]
In fact, it seems that the command is executed if i check it manually with `tmux capture-pane` but the problem is that it only returns just the first line.
If i replace 'cowsay hello' with say 'ls -rtl' it works and all the lines are returned
It i replace 'cowsay hello' with 'ls -rtl | fzf', only the first line is returned too

Any ideas ?

**Comment by lwthatcher** [comment]
have you tried adding a short delay before calling `capture_pane`?

It seems that `capture_pane` returns the text it finds _at the time it's called_. This can lead to **race conditions** when commands from `send_keys()` or `cmd()` might take longer to execute than the call to `capture_pane()`.

### Example:
I encountered the same problem when using it to call a custom script:

**script:** `my-server serve api`
> \*This script just launches a small REST server.  Once initialized it prints the version number, along with some default messages from [Flask](http://flask.pocoo.org/).

I also found that my _.bashrc_ setup can contribute to some delays, my setup has a slight delay so I print a message to the console once it's finished.

#### no delay
``` python
pane.send_keys('my-server serve api')
stuff = pane.capture_pane()
print(stuff)
```
**Output:** `[' my-server serve api']`

#### slight delay
``` python
pane.send_keys('my-server serve api')
time.sleep(2)
stuff = pane.capture_pane()
print(stuff)
```
**Output:** `[' my-server serve api', '.bashrc loaded', '<user>@<host>:/path/to/dir$  my-server serve api']`

#### slightly longer delay
``` python
pane.send_keys('my-server serve api')
time.sleep(5)
stuff = pane.capture_pane()
print(stuff)
```
**Output:** `[' my-server serve api', '.bashrc loaded', '<user>@<host>:/path/to/dir$  my-server serve api', 'LAUNCHING SERVER:  (3.4.3)', ' * Serving Flask app "path/to/dir/server.py"', ' * Environment: production', '   WARNING: Do not use the development server in a production environment.', '   Use a production WSGI server instead.', ' * Debug mode: off', ' * Running on http://127.0.0.1:5050/ (Press CTRL+C to quit)']`

> **Note:** some values such `<user>` and `<host>` were altered above for privacy

**Comment by rockandska** [comment]
Thanks @lwthatcher , didn't tried it yet, but i indeed encounter the same behaviour with another tmux library (https://github.com/jhawthorn/ttytest) and adding a delay of 0.1 between 'send-keys' solved my problems.
I wasn't aware too at first, that 'send-keys' don't wait a return of the command and need to be test manually.
Closing since it seems related to a delay between commands.
Thanks,
