### ISSUE TITLE
Resume the project and Maintain

### ISSUE THREAD

**Issue by tejas15802** [tmux-python/libtmux#338]
Please resume this project and maintain it, I came across this amazing API which I thought of integrating it with my code base but then it doesn't seem to work. Hope it resumes soon 
As the tool didn't work as expected and many had the same issue as mine..

**Comment by tejas15802** [comment]
For some reason tmux server doesn't start on own as expected, but then If I run the tmux server on my own and then use the API I think it works

**Comment by tejas15802** [comment]
Btw, when `pane.send_keys` is used, it sends to the terminal with space

**Comment by tony** [comment]
@tejas15802 Hi! We're looking for help on the project: https://github.com/tmux-python/tmuxp/discussions/290

> For some reason tmux server doesn't start on own as expected, but then If I run the tmux server on my own and then use the API I think it works

I'd need more information, e.g. tmux version, the code you're running

**Comment by tony** [comment]
Here's a recent run of our test suite:

https://github.com/tmux-python/libtmux/runs/3714861439 (tmux 3.2a)


https://user-images.githubusercontent.com/26336/134826634-32d6cc8b-07b2-4564-873e-e11ed69029a4.mp4

This is me running it with no active tmux server.

```python
import libtmux
server = libtmux.Server()

# now start a session
session = server.new_session(session_name='my session')

# a first window is automatically created, so `.new_window()` created a second one
window = session.new_window(window_name='My window')
```

**Comment by tejas15802** [comment]
> Here's a recent run of our test suite:
> 
> https://github.com/tmux-python/libtmux/runs/3714861439 (tmux 3.2a)
> 
>  2021-09-26.17-44-48.-.issue.338.mp4 
> This is me running it with no active tmux server.
> 
> ```python
> import libtmux
> server = libtmux.Server()
> 
> # now start a session
> session = server.new_session(session_name='my session')
> 
> # a first window is automatically created, so `.new_window()` created a second one
> window = session.new_window(window_name='My window')
> ```

Thanks It works, I was following  `README.md`. I followed your example and it works.
