### ISSUE TITLE
New session has to have a name

### ISSUE THREAD

**Issue by qwertimer** [tmux-python/libtmux#399]
Tmux doesn't require a name to create a new session. Each session is created with increasing numeric order. Request option to generate new tmux session without a name.

**Comment by tony** [comment]
Not sure if this is a bug or an enhancement, but this makes sense to me :)

**Comment by tony** [comment]
@qwertimer  I released v0.14.1 ([tag](https://github.com/tmux-python/libtmux/tree/v0.14.1), [PyPI](https://pypi.org/project/libtmux/0.14.1/))

If you upgrade and try again, is anything different?

**Comment by qwertimer** [comment]
Not exactly. It will run with out the name but it forces the name to None. It should just enumerate to 0 and so on. With this fix if you rerun the new_session we have a duplicate session. Essentially what we should do is in Popen just send tmux new-session and it will default to the numbered values.

**Comment by qwertimer** [comment]
or add a check for None. If not run run below.        

 tmux_args: t.Tuple[t.Union[str, int], ...] = (
            "-s%s" % session_name,
            "-P",
            "-F%s" % formats.FORMAT_SEPARATOR.join(tmux_formats),  # output
        )
else run it without the -s flag

**Comment by tony** [comment]
@qwertimer Good catch

**Comment by tony** [comment]
@qwertimer I released v0.14.2 ([tag](https://github.com/tmux-python/libtmux/tree/v0.14.2), [PyPI](https://pypi.org/project/libtmux/0.14.2/))

How about this?

**Comment by qwertimer** [comment]
perfect. Im happy this was fixed so fast. I was going to look at it tonight.
