### ISSUE TITLE
Quickstart's key entry section assumes history suppression is on by default.

### ISSUE THREAD

**Issue by nelsonjchen** [tmux-python/libtmux#403]
https://libtmux.git-pull.com/quickstart.html#sending-commands-to-tmux-panes-remotely mentions history suppression is on by default.

However, the library docs indicate that it is off by default starting in 0.14. https://libtmux.git-pull.com/reference/panes.html#libtmux.Pane.send_keys

**Comment by tony** [comment]
@nelsonjchen Good catch!

**Comment by tony** [comment]
@nelsonjchen Updated via 9a0f9d088192fcce9699c50bf1fd6468bb6bd82e, let me know if that works / is okay.  You are also welcome to submit a PR if you have an improvement

**Comment by nelsonjchen** [comment]
Ah I'm not too familiar with libtmux at the moment to submit a PR. It looks like that works! Thanks!
