### ISSUE TITLE
[dev] pytest not installed in poetry virtual env

### ISSUE THREAD

**Issue by rockandska** [tmux-python/libtmux#404]
HI,

It seems that tests do not use pytest from virtualenv but from the user system and force the user to install the expected pytest version on its env instead of having the right one directly installed in the .venv

```
$ poetry run which py.test
/home/rockandska/.local/bin/py.test

poetry run which python
/home/rockandska/Documents/Git/libtmux/.venv/bin/python
```

Having a pinned pytest version installed in .venv would solve the problem and will help to achieve reproducible test env

**Comment by tony** [comment]
@rockandska What command did you use to install the packages?

Try this:

`poetry install -E "test coverage lint"`

`poetry run which py.test`

**Comment by rockandska** [comment]
My bad, just seen I indeed forgot some commands.....

Sorry for the inconvenience

**Comment by tony** [comment]
Good this got solved!
