### ISSUE TITLE
0.15.3: Issues with pytester fixture

### ISSUE THREAD

**Issue by dvzrv** [tmux-python/libtmux#441]
Hi! When trying to package 0.15.3 on Arch Linux I ran into an issue with the `test_plugin` test:

```
==================================== ERRORS ====================================
________________________ ERROR at setup of test_plugin _________________________
file /build/python-libtmux/src/libtmux-0.15.3/tests/test_pytest_plugin.py, line 8
  def test_plugin(
E       fixture 'pytester' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clear_env, config_file, doctest_namespace, home_path, home_user_name, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, server, session, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, user_path, zshrc
>       use 'pytest --fixtures [testpath]' for help on them.

/build/python-libtmux/src/libtmux-0.15.3/tests/test_pytest_plugin.py:8
=========================== short test summary info ============================
ERROR tests/test_pytest_plugin.py::test_plugin
========================= 92 passed, 1 error in 8.86s ==========================
```

We are currently using python-pytest 7.1.3 on Arch Linux and the fixture should be somehow available. According to the [pytest documentation](https://docs.pytest.org/en/7.1.x/reference/reference.html#std-fixture-pytester) it needs to be added in the configuration file. As you do not include your conftest.py in the sdist tarball, [the configuration is missing](https://github.com/tmux-python/libtmux/blob/master/conftest.py#L14) though. FWIW, the conftest file can just reside in the tests directory.

Looking at the [import of the internal functionality](https://github.com/tmux-python/libtmux/blob/9828540dd9f8074e8d088c5efe707a7db95304cc/tests/test_pytest_plugin.py#L5) from `_pytest` I don't think it is a good idea to rely on it the way it is currently done. The internal implementations of pytest will change and they will break your tests.
It is much better to `from pytest import Pytester`.

**Comment by tony** [comment]
@dvzrv 

I'll look closer after work today (this week, latest) and release a patch at soon as possible

P.S. Are there instructions where I could simulate archlinux packaging / test infrastructure in our GitHub action?

**Comment by tony** [comment]
> Looking at the [import of the internal functionality](https://github.com/tmux-python/libtmux/blob/9828540dd9f8074e8d088c5efe707a7db95304cc/tests/test_pytest_plugin.py#L5) from _pytest I don't think it is a good idea to rely on it the way it is currently done.

Agreed. It's an oversight on my part. 🙏

**Comment by tony** [comment]
> FWIW, the conftest file can just reside in the tests directory.

More complicated than that: https://github.com/tmux-python/libtmux/commit/10d1f9b293b4bf9f353446cb3e9f7b312f786fd9

> ________________________ ERROR collecting test session _________________________
> Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
> It affects the entire test suite instead of just below the conftest as expected.
>   /home/runner/work/libtmux/libtmux/src/libtmux/conftest.py
> Please move it to a top level conftest file at the rootdir:
>   /home/runner/work/libtmux/libtmux
> For more information, visit:
>   https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files

**Comment by tony** [comment]
@dvzrv If you try [v0.15.4](https://pypi.org/project/libtmux/0.15.4/), is it any better?

(merged changes from #442)

**Comment by tony** [comment]
@dvzrv Is v0.15.4 (or v0.15.7, which is the latest) any better?

**Comment by dvzrv** [comment]
0.15.4 worked, thanks!
