### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by tony** [tmux-python/libtmux#46]
(See also https://github.com/tony/tmuxp/issues/264)

This project is currently licensed BSD 3-Clause.  Apologies if this causes any interruption.

I would like to relicense the project under MIT.  If you agree to licensing your contribution(s) to libtmux under the MIT license, please reply.

- [x] @kaushalmodi
- [x] @tek
- [ ] @huwenchao
- [x] @gandelman-a
- [x] @robled
- [x] @dankrause
- [x] @leezu
- [x] @sloria
- [x] @minijackson
- [x] @geekli

**Comment by leezu** [comment]
Fine with me. Thanks for your work on this.

**Comment by gandelman-a** [comment]
No problem from me, thanks for the heads up!

**Comment by minijackson** [comment]
Sounds perfect for me ;-)

**Comment by kaushalmodi** [comment]
Fine by me, thanks.

**Comment by sloria** [comment]
Sounds good to me.

**Comment by dankrause** [comment]
A agree with a switch to the MIT license.

**Comment by geekli** [comment]
No problem

**Comment by tony** [comment]
Great so far. Only 3 signatures left.

@tek @huwenchao @robled, do you agree to license your contributions to libtmux under the [MIT license](https://opensource.org/licenses/MIT)? If you do, reply that you agree!

**Comment by tek** [comment]
sure!

**Comment by robled** [comment]
Approved.

**Comment by tony** [comment]
@huwenchao, do you approve the license change?

**Comment by dankrause** [comment]
@huwenchao has contributed one single line to this project:

https://github.com/tony/libtmux/blame/master/README.rst#L101

Perhaps there is something we can do to push the MIT licensing forward without that contribution.

**Comment by tony** [comment]
It's been several months of asking. 86e1089a5891b52a139257f4e0dd699c0577028c by @huwenchao is a typo. This is getting out of hand. We obviously want spelling corrections, but we can't hold up a LICENSE change forever.

I'm going to revert @huwenchao's typo fix. Then redo the typo myself (by inference licensing it MIT), thanking @huwenchao, linking to the original ref (licensed BSD).

**Comment by tony** [comment]
See the revert at 350248c.

See the typo fixed by me, licensed MIT, thanking @huwenchao at 928ecc1.
