### ISSUE TITLE
The parse of list-panes output breaks when the screen buffer contains pipe symbol

### ISSUE THREAD

**Issue by hongwen000** [tmux-python/libtmux#472]
When there are pipe symbols in the screen buffer, the buffer_sample field in the output of "tmux list-session" may contain pipe symbols. 

In the "fetch_objs" function of neo.py, the "obj_formatters" use pipe symbols as the delimiter between fields when parsing the output of "tmux list-session", causing an error in the parsing when pipe symbols are present in the buffer_sample field. 

This results in failure of all functions that rely on "fetch_objs" such as creating and listing sessions.

**Comment by tony** [comment]
@hongwen: I followed up with you [here](https://github.com/tmux-python/libtmux/pull/473#issuecomment-1407426187), Can you try this PR or that environmental variable out and see if it allieves the issue?

**Comment by tony** [comment]
@hongwen000 If you try [v0.21.0](https://pypi.org/project/libtmux/0.21.0/) (which includes #475), is anything different?

**Comment by hongwen000** [comment]
@tony Yes, I have upgraded both tmuxp and libtmux, and now they are working well. Thanks for your following up.

**Comment by tony** [comment]
@hongwen000 Excellent! Back in action now!

I will close this issue for now. Is #473 settled as well?

**Comment by hongwen000** [comment]
@tony Yes. I have closed that pull request.

**Comment by tony** [comment]
@hongwen000 Good to know this is fixed! I will close this for now. Let me know if this persists!
