### ISSUE TITLE
Do not send-keys literally by default

### ISSUE THREAD

**Issue by ritiek** [tmux-python/libtmux#88]
I noticed that libtmux sends keys to a window pane literally. A minimal reproduction:
```python
import libtmux

server = libtmux.Server()
session = server.new_session('happy_session')
window = session.new_window('happy_window')
pane = window.attached_pane

# instead of KeyboardInterrupt, libtmux sends 'C-c'
pane.send_keys('C-c')
```

tmux uses `-l` to specifiy if the keys are to be sent literally:
```bash
# not literally
tmux send-keys -t happy_session C-c

# literally
tmux send-keys -l -t happy_session C-c
```

It would be nice if there were an option to override this behavior in libtmux and preferably set as defaults `Pane.send_keys(literal=False)` just as in tmux.

**Comment by ritiek** [comment]
I was messing around a bit and I think I figured what's going on.

libtmux prefixes the command with *a blank space*, so special events like `C-c` become `<space>C-c` which causes tmux to take it literally.

A workaround for the moment would be to pass `suppress_history=False` in `Pane.send_keys()`.

**Comment by ritiek** [comment]
The problem still remains about sending keys literally while `suppress_history=False`.

**Comment by tony** [comment]
I'm pinning this. 

Sorry for the late response, I am having issues keeping up wit the project. I'm seeking maintainers @ https://github.com/tony/tmuxp/issues/290. If you (or someone you know) may be interested in helping maintain libtmux or tmuxp, feel free to contact me by email or in the https://github.com/tony/tmuxp/issues/290 issue.
